name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests ${{matrix.sdk}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        redis-version: [5, 6, 7]
        dart-sdk: ['stable', 'beta']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-sdk }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: redis-server --version
      - id: install
        name: Install dependencies
        run: dart pub get
      - name: Analyze code
        run: dart analyze --fatal-infos
        if: always() && steps.install.outcome == 'success'
      - name: Run tests
        run: dart test
        if: always() && steps.install.outcome == 'success'
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
